### PR TITLE
Adds Extension to Dataset; Adds Index to, Removes Class and Version from Dimension

### PR DESCRIPTION
**Pull request by jmouradi**
This revision: 
1. Removes `class` and `version` from the `Dimension` class, as the `Dimension` class is used internally to the `Dataset` class; the `dimension` field within `dataset` in the [schema](https://json-stat.org/format/schema/2.0/) does not include these and the presence of these fields is invalid according to the json-stat.org [validator](https://json-stat.org/format/validator/).
2. Adds the ability to provide only an `index` without a `label` in `dimension`. 
3. Adds the ability to supply an `extension` field to a `dataset`. 

Item (1) is for correctness (though a separate, top-level `dimension` response class will need to be created), while items (2) and (3) are features required for our own minimum viable prototyping and iteration.

Because this is not a confirmed release, pom.xml is not bumped.

Please let me know what changes you'd like to see before making this merge!

### CODE REVIEW

**Comment by hadrienk** [comment]
Hi James, thank you.

I was planning on using polymorphism (@JsonTypeInfo) to handle the top-level. Haven't yet figured it all out but your change makes sense.

Regarding the extension field I see that you chose to use a Map<String, String>, yet the [format description](https://json-stat.org/format/#extension) states that it is an object. We could simply set this as a Map<String, ?> and maybe provide nice accessors as it is recommended?

**Comment by jmouradi** [comment]
Hi Hadrien,
    Thanks for taking a look! I have removed the `<String, String>` typing from Extension, and also made it nullable. What do you think of the current accessor, [getExtension](https://github.com/statisticsnorway/json-stat.java/pull/4/files#diff-af63729710dae6c221d9d305304faca0R89)?

**Comment by hadrienk** [comment]
@jmouradi I am looking in details now as I am pushing some changes on the develop branch. I think the most flexible way to handle the extension is to rely on the jackson ObjectNode type. I will make the necessary changes.

**Comment by hadrienk** [comment]
Merged in develop.

**Pull request closed without merging**
